apiVersion: v1
kind: Pod
metadata:
  name: first-test-pod
  labels:
    name: first-test-pod
spec:
  containers:
  - name: first-test-pod
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080