apiVersion: v1
kind: Service
metadata:
  name: nginx-headless
spec:
  clusterIP: None
  selector:
    app: nginx-sts
  ports:
  - port: 80
    targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-sts
  ports:
  - port: 80
    targetPort: 80

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-sts
spec:
  serviceName: nginx-headless
  replicas: 2
  selector:
    matchLabels:
      app: nginx-sts
  template:
    metadata:
      labels:
        app: nginx-sts
    spec:
      volumes:
      - name: temp-vol
        emptyDir: {}
      initContainers:
      - name: init-container-1
        image: busybox
        volumeMounts:
        - name: temp-vol
          mountPath: /temp
        command: ["/bin/sh", "-c"]
        args: ["echo Hello from container $HOSTNAME >> /temp/index.html"]
      containers:
      - name: nginx-sts
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: temp-vol
          mountPath: /usr/share/nginx/html
        - name: www
          mountPath: /usr/share/nginx
    
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Mi